import type { BugContext, GitInfo } from '../types/index.js';

/**
 * Formats bug context into Claude-friendly markdown
 */
export function formatBugReport(context: BugContext, gitInfo?: GitInfo | null): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Bug Report - ${context.timestamp}`);
  sections.push('');

  // Description
  if (context.description) {
    sections.push(`## Description`);
    sections.push('');
    sections.push(context.description);
    sections.push('');
  }

  // Screenshot
  if (context.screenshot) {
    sections.push(`## Screenshot`);
    sections.push('');
    sections.push(`![Screenshot](${context.screenshot})`);
    sections.push('');
    sections.push(`Path: \`${context.screenshot}\``);
    sections.push('');
  }

  // Git Information
  if (gitInfo) {
    sections.push(`## Git Context`);
    sections.push('');
    sections.push(`- **Branch:** \`${gitInfo.branch}\``);
    sections.push(`- **Commit:** \`${gitInfo.commit}\``);
    sections.push(`- **Has Changes:** ${gitInfo.hasChanges ? '✓ Yes' : '✗ No'}`);
    sections.push('');

    if (gitInfo.recentCommits && gitInfo.recentCommits.length > 0) {
      sections.push(`### Recent Commits`);
      sections.push('');
      sections.push('```');
      gitInfo.recentCommits.forEach(commit => sections.push(commit));
      sections.push('```');
      sections.push('');
    }

    if (gitInfo.status && gitInfo.status.trim()) {
      sections.push(`### Git Status`);
      sections.push('');
      sections.push('```');
      sections.push(gitInfo.status);
      sections.push('```');
      sections.push('');
    }

    if (gitInfo.diff && gitInfo.diff.trim()) {
      sections.push(`### Uncommitted Changes`);
      sections.push('');
      sections.push('```diff');
      sections.push(gitInfo.diff);
      sections.push('```');
      sections.push('');
    }
  }

  // Browser Console Errors
  if (context.browserInfo?.consoleErrors && context.browserInfo.consoleErrors.length > 0) {
    sections.push(`## Browser Console Errors`);
    sections.push('');
    sections.push('```');
    context.browserInfo.consoleErrors.forEach(error => sections.push(error));
    sections.push('```');
    sections.push('');
  }

  // Browser Info
  if (context.browserInfo?.url) {
    sections.push(`## Browser Context`);
    sections.push('');
    sections.push(`- **URL:** ${context.browserInfo.url}`);
    sections.push('');

    if (context.browserInfo.networkErrors && context.browserInfo.networkErrors.length > 0) {
      sections.push(`### Network Errors`);
      sections.push('');
      context.browserInfo.networkErrors.forEach(error => {
        sections.push(`- ${error}`);
      });
      sections.push('');
    }
  }

  // System Info
  if (context.systemInfo) {
    sections.push(`## System Info`);
    sections.push('');
    sections.push(`- **Platform:** ${context.systemInfo.platform}`);
    sections.push(`- **Architecture:** ${context.systemInfo.arch}`);
    if (context.systemInfo.nodeVersion) {
      sections.push(`- **Node:** ${context.systemInfo.nodeVersion}`);
    }
    if (context.systemInfo.bunVersion) {
      sections.push(`- **Bun:** ${context.systemInfo.bunVersion}`);
    }
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*Generated by VibeDev Toolkit*');
  sections.push('');

  return sections.join('\n');
}

/**
 * Formats error message in a human-readable way
 */
export function formatError(error: string): string {
  const lines: string[] = [];

  lines.push('## Error Analysis');
  lines.push('');
  lines.push('```');
  lines.push(error);
  lines.push('```');
  lines.push('');

  // Add helpful context
  lines.push('### What this error means:');
  lines.push('');
  lines.push('> [AI analysis would go here]');
  lines.push('');

  return lines.join('\n');
}

/**
 * Creates a summary for clipboard
 */
export function formatClipboardSummary(context: BugContext): string {
  const parts: string[] = [];

  if (context.description) {
    parts.push(context.description);
    parts.push('');
  }

  if (context.screenshot) {
    parts.push(`Screenshot: ${context.screenshot}`);
    parts.push('');
  }

  if (context.gitDiff) {
    parts.push('Git changes:');
    parts.push('```diff');
    parts.push(context.gitDiff.substring(0, 500)); // First 500 chars
    parts.push('```');
  }

  return parts.join('\n');
}
